<h1>PANDAS LIBRARY</H1>

In [2]:
#pandas is a library used for data manipulation and analysis. It provides data structures and functions needed to manipulate structured data, such as tabular data in the form of DataFrames.
#it is of two types 1) series(single column of data)
#                   2) dataframe
import pandas as pd
import numpy as np

In [ ]:
#creating series
s=pd.Series([1,2,3,4,5])
print(s)
type(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

:

In [90]:
s=pd.Series(['a','b','c','d','e'])
print(s)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [91]:
s=pd.Series(['a','b','c','d','e'],index =[1,2,3,11,5]) # we can set index of objects according to us
print(s)

1     a
2     b
3     c
11    d
5     e
dtype: object

In [92]:
print(s[11]) # indexing
print(s[1:4]) #slicing (by default we have to give the general series of index while slicing)

d
2     b
3     c
11    d
dtype: object

In [93]:
#tuple to series
t= pd.Series((13,5,3,5)) 
print(t)

0    13
1     5
2     3
3     5
dtype: int64

In [94]:
#set to series
s=pd.Series({2,3,4,4,5,})
s# set can't be used as series it is unordered

TypeError: 'set' type is unordered

In [ ]:
#dictonary to series
d=pd.Series({'a':1,'b':2,'c':3})
print(d) #key becomes index position and value becomes the object
d=pd.Series({'a':1,'b':2,'c':3},index=['e','f','a','b'])
print(d)
d['b']# indexing
d['a':'b':1] #slicing

a    1
b    2
c    3
dtype: int64
e    NaN
f    NaN
a    1.0
b    2.0
dtype: float64

a    1.0
b    2.0
dtype: float64

In [ ]:
#creating dataframe
d={'name':['ram','hari','sita','gita'],'roll':[101,102,103,104],'course':['AIML','PYTHON','DSA','C']} #dataframes are created using dictionary
print(d)
df=pd.DataFrame(d)
print(df)

{'name': ['ram', 'hari', 'sita', 'gita'], 'roll': [101, 102, 103, 104], 'course': ['AIML', 'PYTHON', 'DSA', 'C']}
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
print(df.name[2]) #indexing syntax:- var.colname[index]
print(df.iloc[::1]) #this is slicing in dataframes
print (df.iloc[2::])
print(df.iloc[::,2])

sita
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C
   name  roll course
2  sita   103    DSA
3  gita   104      C
0      AIML
1    PYTHON
2       DSA
3         C
Name: course, dtype: object

In [ ]:
print(df.head()) # it will give us the first 5 rows of dataframe by default and if we want to give the number of rows we want to see then we can give the number in the head function like this df.head(3) it will give us the first 3 rows of dataframe
print(df.tail()) # it will give us the last 5 rows of dataframe by default and if we want to give the number of rows we want to see then we can give the number in the tail function like this df.tail(3) it will give us the last 3 rows of dataframe

   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
df.sample(3) # it will give us a random row from the dataframe and if we want to give the number of rows we want to see then we can give the number in the sample function like this df.sample(3) it will give us 3 random rows from the dataframe

   name  roll  course
0   ram   101    AIML
3  gita   104       C
1  hari   102  PYTHON

In [ ]:
df=df.rename(columns={'name':'Name','roll':'Roll','course':'Course'}) # renaming the columns of dataframe
print(df)

   Name  Roll  Course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
df=df.set_index('Roll') # setting the index of dataframe to name column
print(df)
#df=df.set_index('Course',inplace=True) # setting the index of dataframe to course column and inplace is used to make the changes in the original dataframe
#print(df)

      Name  Course
Roll
101    ram    AIML
102   hari  PYTHON
103   sita     DSA
104   gita       C

In [ ]:
df.reset_index('Roll')
df

      Name  Course
Roll
101    ram    AIML
102   hari  PYTHON
103   sita     DSA
104   gita       C

In [ ]:
df=pd.DataFrame({'Days':[1,2,3,4,5],'Places':['Paris','Tokyo',np.nan,'New York','Sydney'],'Visitors':[3425,4523,3244,4324,4342]})
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3       NaN      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False    True     False
3  False   False     False
4  False   False     False

In [ ]:
df.isnull().sum() #this is used to check the no.of missing values

Days        0
Places      1
Visitors    0
dtype: int64

In [ ]:
df.Places.fillna('Delhi')
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3       NaN      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
df.Places.fillna('Delhi',inplace=True)
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3     Delhi      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df.dtypes

Days         int64
Places      object
Visitors     int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   Places    5 non-null      object
 2   Visitors  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
df.Places.unique()

array(['Paris', 'Tokyo', 'Delhi', 'New York', 'Sydney'], dtype=object)

In [ ]:
df.columns

Index(['Days', 'Places', 'Visitors'], dtype='object')

In [ ]:
for i in df.columns:
    print(df[i].unique())

[1 2 3 4 5]
['Paris' 'Tokyo' 'Delhi' 'New York' 'Sydney']
[3425 4523 3244 4324 4342]

In [ ]:
df.Visitors.mean()

np.float64(3971.6)

In [ ]:
df.Visitors.min()

3244

In [ ]:
print(df[df["Visitors"] == df["Visitors"].min()])

   Days Places  Visitors
2     3  Delhi      3244

In [ ]:
df.describe(include='all')

            Days Places    Visitors
count   5.000000      5     5.00000
unique       NaN      5         NaN
top          NaN  Paris         NaN
freq         NaN      1         NaN
mean    3.000000    NaN  3971.60000
std     1.581139    NaN   590.25359
min     1.000000    NaN  3244.00000
25%     2.000000    NaN  3425.00000
50%     3.000000    NaN  4324.00000
75%     4.000000    NaN  4342.00000
max     5.000000    NaN  4523.00000

IRIS DATASET

In [ ]:
iris=pd.read_csv(r"C:\Users\mishr\Downloads\iris\iris.data")
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
iris=pd.read_csv(r"C:\Users\mishr\Downloads\iris\iris.data",header=None) # if we want to give the column names then we can give the column names in the header parameter like this header=['sepal_length','sepal_width','petal_length','petal_width','class']
iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris.columns=['length','sepal width','petal length','petal width','_class_' ]
iris

     length  sepal width  petal length  petal width         _class_
0       5.1          3.5           1.4          0.2     Iris-setosa
1       4.9          3.0           1.4          0.2     Iris-setosa
2       4.7          3.2           1.3          0.2     Iris-setosa
3       4.6          3.1           1.5          0.2     Iris-setosa
4       5.0          3.6           1.4          0.2     Iris-setosa
..      ...          ...           ...          ...             ...
145     6.7          3.0           5.2          2.3  Iris-virginica
146     6.3          2.5           5.0          1.9  Iris-virginica
147     6.5          3.0           5.2          2.0  Iris-virginica
148     6.2          3.4           5.4          2.3  Iris-virginica
149     5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris.head()

   length  sepal width  petal length  petal width      _class_
0     5.1          3.5           1.4          0.2  Iris-setosa
1     4.9          3.0           1.4          0.2  Iris-setosa
2     4.7          3.2           1.3          0.2  Iris-setosa
3     4.6          3.1           1.5          0.2  Iris-setosa
4     5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
iris.tail()

     sepal length  sepal width  petal length  petal width         _class_
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
iris.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
_class_         0
dtype: int64

In [ ]:
iris.dtypes

sepal length    float64
sepal width     float64
petal length    float64
petal width     float64
_class_          object
dtype: object

In [ ]:
iris.info

<bound method DataFrame.info of      sepal length  sepal width  petal length  petal width         _class_
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [ ]:
iris['sepal length'].unique()# for col_name having space between name we have to write like this

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [ ]:
for i in iris.columns:
    print(i,':',iris[i].unique(),'\n')

sepal length : [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]

sepal width : [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]

petal length : [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2]

petal width : [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3]

_class_ : ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [ ]:
iris.describe(include='all')

        sepal length  sepal width  petal length  petal width      _class_
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [ ]:
iris.length.value_counts

<bound method IndexOpsMixin.value_counts of 0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: length, Length: 150, dtype: float64>

AUTO MPG DATASET

In [ ]:
auto=pd.read_csv(r"C:\Users\mishr\Downloads\auto+mpg\auto-mpg.data",header=None,delim_whitespace=True)
auto

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]

In [ ]:
auto.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [ ]:
auto.columns=['mpg','cylinder','disp','HP','weight','acc','modelyr','origin','car name']
auto

,mpg,cylinder,disp,HP,weight,acc,modelyr,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [ ]:
auto.dtypes

mpg         float64
cylinder      int64
disp        float64
HP           object
weight      float64
acc         float64
modelyr       int64
origin        int64
car name     object
dtype: object

In [ ]:
auto.describe(include='all')

,mpg,cylinder,disp,HP,weight,acc,modelyr,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150.0,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [ ]:
auto.mpg.value_counts

<bound method IndexOpsMixin.value_counts of 0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64>

In [ ]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cylinder  398 non-null    int64
 2   disp      398 non-null    float64
 3   HP        398 non-null    object
 4   weight    398 non-null    float64
 5   acc       398 non-null    float64
 6   modelyr   398 non-null    int64
 7   origin    398 non-null    int64
 8   car name  398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [ ]:
for i in auto.columns:
    print(i,':','\n',auto[i].unique(),'\n')

mpg :
 [18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ]

cylinder :
 [8 4 6 3 5]

disp :
 [307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  90.  231.  262.  134.  119.  171.  115.  101.  305.   85.  130.  168.
 111.  260.  151.  146.   80.   78.  105.  131.  163.   89.  267.   86.
 183.  141.  173.  135.   81.  100.  145.  112.  181.  144. ]

HP :
 ['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']

weight :
 [3504. 3693. 3436. 3433. 3449. 4341. 4354. 4312. 4425. 3850. 3563. 3609.
 3761. 3086. 2372. 2833. 2774. 2587. 2130. 1835. 2672. 2430. 2375. 2234.
 2648. 4615. 4376. 4382. 4732. 2264. 2228. 2046. 2634. 3439. 3329. 3302.
 3288. 4209. 4464. 4154. 4096. 4955. 4746. 5140. 2962. 2408. 3282. 3139.
 2220. 2123. 2074. 2065. 1773. 1613. 1834. 1955. 2278. 2126. 2254. 2226.
 4274. 4385. 4135. 4129. 3672. 4633. 4502. 4456. 4422. 2330. 3892. 4098.
 4294. 4077. 2933. 2511. 2979. 2189. 2395. 2288. 2506. 2164. 2100. 4100.
 3988. 4042. 3777. 4952. 4363. 4237. 4735. 4951. 3821. 3121. 3278. 2945.
 3021. 2904. 1950. 4997. 4906. 4654. 4499. 2789. 2279. 2401. 2379. 2124.
 2310. 2472. 2265. 4082. 4278. 1867. 2158. 2582. 2868. 3399. 2660. 2807.
 3664. 3102. 2875. 2901. 3336. 2451. 1836. 2542. 3781. 3632. 3613. 4141.
 4699. 4457. 4638. 4257. 2219. 1963. 2300. 1649. 2003. 2125. 2108. 2246.
 2489. 2391. 2000. 3264. 3459. 3432. 3158. 4668. 4440. 4498. 4657. 3907.
 3897. 3730. 3785. 3039. 3221. 3169. 2171. 2639. 2914. 2592. 2702. 2223.
 2545. 2984. 1937. 3211. 2694. 2957. 2671. 1795. 2464. 2572. 2255. 2202.
 4215. 4190. 3962. 3233. 3353. 3012. 3085. 2035. 3651. 3574. 3645. 3193.
 1825. 1990. 2155. 2565. 3150. 3940. 3270. 2930. 3820. 4380. 4055. 3870.
 3755. 2045. 1945. 3880. 4060. 4140. 4295. 3520. 3425. 3630. 3525. 4220.
 4165. 4325. 4335. 1940. 2740. 2755. 2051. 2075. 1985. 2190. 2815. 2600.
 2720. 1800. 2070. 3365. 3735. 3570. 3535. 3155. 2965. 3430. 3210. 3380.
 3070. 3620. 3410. 3445. 3205. 4080. 2560. 2230. 2515. 2745. 2855. 2405.
 2830. 3140. 2795. 2135. 3245. 2990. 2890. 3265. 3360. 3840. 3725. 3955.
 3830. 4360. 4054. 3605. 1925. 1975. 1915. 2670. 3530. 3900. 3190. 3420.
 2200. 2150. 2020. 2595. 2700. 2556. 2144. 1968. 2120. 2019. 2678. 2870.
 3003. 3381. 2188. 2711. 2434. 2110. 2800. 2085. 2335. 2950. 3250. 1850.
 2145. 1845. 2910. 2420. 2500. 2905. 2290. 2490. 2635. 2620. 2725. 2385.
 1755. 1875. 1760. 2050. 2215. 2380. 2320. 2210. 2350. 2615. 3230. 3160.
 2900. 3415. 3060. 3465. 2605. 2640. 2575. 2525. 2735. 2865. 3035. 1980.
 2025. 1970. 2160. 2205. 2245. 1965. 1995. 3015. 2585. 2835. 2665. 2370.
 2790. 2295. 2625.]

acc :
 [12.  11.5 11.  10.5 10.   9.   8.5  8.   9.5 15.  15.5 16.  14.5 20.5
 17.5 12.5 14.  13.5 18.5 19.  13.  19.5 18.  17.  23.5 16.5 21.  16.9
 14.9 17.7 15.3 13.9 12.8 15.4 17.6 22.2 22.1 14.2 17.4 16.2 17.8 12.2
 16.4 13.6 15.7 13.2 21.9 16.7 12.1 14.8 18.6 16.8 13.7 11.1 11.4 18.2
 15.8 15.9 14.1 21.5 14.4 19.4 19.2 17.2 18.7 15.1 13.4 11.2 14.7 16.6
 17.3 15.2 14.3 20.1 24.8 11.3 12.9 18.8 18.1 17.9 21.7 23.7 19.9 21.8
 13.8 12.6 16.1 20.7 18.3 20.4 19.6 17.1 15.6 24.6 11.6]

modelyr :
 [70 71 72 73 74 75 76 77 78 79 80 81 82]

origin :
 [1 3 2]

car name :
 ['chevrolet chevelle malibu' 'buick skylark 320' 'plymouth satellite'
 'amc rebel sst' 'ford torino' 'ford galaxie 500' 'chevrolet impala'
 'plymouth fury iii' 'pontiac catalina' 'amc ambassador dpl'
 'dodge challenger se' "plymouth 'cuda 340" 'chevrolet monte carlo'
 'buick estate wagon (sw)' 'toyota corona mark ii' 'plymouth duster'
 'amc hornet' 'ford maverick' 'datsun pl510'
 'volkswagen 1131 deluxe sedan' 'peugeot 504' 'audi 100 ls' 'saab 99e'
 'bmw 2002' 'amc gremlin' 'ford f250' 'chevy c20' 'dodge d200' 'hi 1200d'
 'chevrolet vega 2300' 'toyota corona' 'ford pinto'
 'plymouth satellite custom' 'ford torino 500' 'amc matador'
 'pontiac catalina brougham' 'dodge monaco (sw)'
 'ford country squire (sw)' 'pontiac safari (sw)'
 'amc hornet sportabout (sw)' 'chevrolet vega (sw)' 'pontiac firebird'
 'ford mustang' 'mercury capri 2000' 'opel 1900' 'peugeot 304' 'fiat 124b'
 'toyota corolla 1200' 'datsun 1200' 'volkswagen model 111'
 'plymouth cricket' 'toyota corona hardtop' 'dodge colt hardtop'
 'volkswagen type 3' 'chevrolet vega' 'ford pinto runabout'
 'amc ambassador sst' 'mercury marquis' 'buick lesabre custom'
 'oldsmobile delta 88 royale' 'chrysler newport royal' 'mazda rx2 coupe'
 'amc matador (sw)' 'chevrolet chevelle concours (sw)'
 'ford gran torino (sw)' 'plymouth satellite custom (sw)'
 'volvo 145e (sw)' 'volkswagen 411 (sw)' 'peugeot 504 (sw)'
 'renault 12 (sw)' 'ford pinto (sw)' 'datsun 510 (sw)'
 'toyouta corona mark ii (sw)' 'dodge colt (sw)'
 'toyota corolla 1600 (sw)' 'buick century 350' 'chevrolet malibu'
 'ford gran torino' 'dodge coronet custom' 'mercury marquis brougham'
 'chevrolet caprice classic' 'ford ltd' 'plymouth fury gran sedan'
 'chrysler new yorker brougham' 'buick electra 225 custom'
 'amc ambassador brougham' 'plymouth valiant' 'chevrolet nova custom'
 'volkswagen super beetle' 'ford country' 'plymouth custom suburb'
 'oldsmobile vista cruiser' 'toyota carina' 'datsun 610' 'maxda rx3'
 'mercury capri v6' 'fiat 124 sport coupe' 'chevrolet monte carlo s'
 'pontiac grand prix' 'fiat 128' 'opel manta' 'audi 100ls' 'volvo 144ea'
 'dodge dart custom' 'saab 99le' 'toyota mark ii' 'oldsmobile omega'
 'chevrolet nova' 'datsun b210' 'chevrolet chevelle malibu classic'
 'plymouth satellite sebring' 'buick century luxus (sw)'
 'dodge coronet custom (sw)' 'audi fox' 'volkswagen dasher' 'datsun 710'
 'dodge colt' 'fiat 124 tc' 'honda civic' 'subaru' 'fiat x1.9'
 'plymouth valiant custom' 'mercury monarch' 'chevrolet bel air'
 'plymouth grand fury' 'buick century' 'chevroelt chevelle malibu'
 'plymouth fury' 'buick skyhawk' 'chevrolet monza 2+2' 'ford mustang ii'
 'toyota corolla' 'pontiac astro' 'volkswagen rabbit' 'amc pacer'
 'volvo 244dl' 'honda civic cvcc' 'fiat 131' 'capri ii' 'renault 12tl'
 'dodge coronet brougham' 'chevrolet chevette' 'chevrolet woody'
 'vw rabbit' 'dodge aspen se' 'ford granada ghia' 'pontiac ventura sj'
 'amc pacer d/l' 'datsun b-210' 'volvo 245' 'plymouth volare premier v8'
 'mercedes-benz 280s' 'cadillac seville' 'chevy c10' 'ford f108'
 'dodge d100' 'honda accord cvcc' 'buick opel isuzu deluxe'
 'renault 5 gtl' 'plymouth arrow gs' 'datsun f-10 hatchback'
 'oldsmobile cutlass supreme' 'dodge monaco brougham'
 'mercury cougar brougham' 'chevrolet concours' 'buick skylark'
 'plymouth volare custom' 'ford granada' 'pontiac grand prix lj'
 'chevrolet monte carlo landau' 'chrysler cordoba' 'ford thunderbird'
 'volkswagen rabbit custom' 'pontiac sunbird coupe'
 'toyota corolla liftback' 'ford mustang ii 2+2' 'dodge colt m/m'
 'subaru dl' 'datsun 810' 'bmw 320i' 'mazda rx-4'
 'volkswagen rabbit custom diesel' 'ford fiesta' 'mazda glc deluxe'
 'datsun b210 gx' 'oldsmobile cutlass salon brougham' 'dodge diplomat'
 'mercury monarch ghia' 'pontiac phoenix lj' 'ford fairmont (auto)'
 'ford fairmont (man)' 'plymouth volare' 'amc concord'
 'buick century special' 'mercury zephyr' 'dodge aspen' 'amc concord d/l'
 'buick regal sport coupe (turbo)' 'ford futura' 'dodge magnum xe'
 'datsun 510' 'dodge omni' 'toyota celica gt liftback' 'plymouth sapporo'
 'oldsmobile starfire sx' 'datsun 200-sx' 'audi 5000' 'volvo 264gl'
 'saab 99gle' 'peugeot 604sl' 'volkswagen scirocco' 'honda accord lx'
 'pontiac lemans v6' 'mercury zephyr 6' 'ford fairmont 4'
 'amc concord dl 6' 'dodge aspen 6' 'ford ltd landau'
 'mercury grand marquis' 'dodge st. regis' 'chevrolet malibu classic (sw)'
 'chrysler lebaron town @ country (sw)' 'vw rabbit custom'
 'maxda glc deluxe' 'dodge colt hatchback custom' 'amc spirit dl'
 'mercedes benz 300d' 'cadillac eldorado' 'plymouth horizon'
 'plymouth horizon tc3' 'datsun 210' 'fiat strada custom'
 'buick skylark limited' 'chevrolet citation' 'oldsmobile omega brougham'
 'pontiac phoenix' 'toyota corolla tercel' 'datsun 310' 'ford fairmont'
 'audi 4000' 'toyota corona liftback' 'mazda 626' 'datsun 510 hatchback'
 'mazda glc' 'vw rabbit c (diesel)' 'vw dasher (diesel)'
 'audi 5000s (diesel)' 'mercedes-benz 240d' 'honda civic 1500 gl'
 'renault lecar deluxe' 'vokswagen rabbit' 'datsun 280-zx' 'mazda rx-7 gs'
 'triumph tr7 coupe' 'ford mustang cobra' 'honda accord'
 'plymouth reliant' 'dodge aries wagon (sw)' 'toyota starlet'
 'plymouth champ' 'honda civic 1300' 'datsun 210 mpg' 'toyota tercel'
 'mazda glc 4' 'plymouth horizon 4' 'ford escort 4w' 'ford escort 2h'
 'volkswagen jetta' 'renault 18i' 'honda prelude' 'datsun 200sx'
 'peugeot 505s turbo diesel' 'volvo diesel' 'toyota cressida'
 'datsun 810 maxima' 'oldsmobile cutlass ls' 'ford granada gl'
 'chrysler lebaron salon' 'chevrolet cavalier' 'chevrolet cavalier wagon'
 'chevrolet cavalier 2-door' 'pontiac j2000 se hatchback' 'dodge aries se'
 'ford fairmont futura' 'amc concord dl' 'volkswagen rabbit l'
 'mazda glc custom l' 'mazda glc custom' 'plymouth horizon miser'
 'mercury lynx l' 'nissan stanza xe' 'honda civic (auto)' 'datsun 310 gx'
 'buick century limited' 'oldsmobile cutlass ciera (diesel)'
 'chrysler lebaron medallion' 'ford granada l' 'toyota celica gt'
 'dodge charger 2.2' 'chevrolet camaro' 'ford mustang gl' 'vw pickup'
 'dodge rampage' 'ford ranger' 'chevy s-10']

In [ ]:
for i in auto.columns:
    print(i,':',sum(auto[i]=='?'))

mpg : 0
cylinder : 0
disp : 0
HP : 6
weight : 0
acc : 0
modelyr : 0
origin : 0
car name : 0

In [ ]:
auto.HP.replace('?',np.nan,inplace=True)
auto

,mpg,cylinder,disp,HP,weight,acc,modelyr,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [ ]:
for i in auto.columns:
    print(i,':',sum(auto[i]=='?'))

mpg : 0
cylinder : 0
disp : 0
HP : 0
weight : 0
acc : 0
modelyr : 0
origin : 0
car name : 0

In [ ]:
auto.dtypes

mpg         float64
cylinder      int64
disp        float64
HP           object
weight      float64
acc         float64
modelyr       int64
origin        int64
car name     object
dtype: object

In [ ]:
auto.HP=auto.HP.astype(float)

In [ ]:
auto.dtypes

mpg         float64
cylinder      int64
disp        float64
HP          float64
weight      float64
acc         float64
modelyr       int64
origin        int64
car name     object
dtype: object

In [ ]:
auto.isnull().sum()

mpg         0
cylinder    0
disp        0
HP          6
weight      0
acc         0
modelyr     0
origin      0
car name    0
dtype: int64

In [ ]:
d=auto.describe(include='all')

In [ ]:
auto.HP.fillna(d[HP][4],inplace=True)

In [ ]:
auto.isnull().sum()

mpg         0
cylinder    0
disp        0
HP          0
weight      0
acc         0
modelyr     0
origin      0
car name    0
dtype: int64

<pre>Data cleaning<br>
1)read the data<br>
2)rename the col name if req<br>
3)check missing or null values<br>
4)check datatype/info<br>
5)check unique values<br>
6)replace the missing values<br>
7)by taking the value from the describe value</pre>

ADULT DATASET

In [ ]:
adult=pd.read_csv(r"C:\Users\mishr\Downloads\adult\adult.data",header=None,delim_whitespace=True)
adult

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.columns= ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','nativecountry','income']
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
adult.dtypes

age               object
workclass         object
fnlwgt            object
education         object
education-num     object
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain      object
capital-loss      object
hours-per-week    object
native-country    object
income            object
dtype: object

In [ ]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  object
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  object
 3   education       32561 non-null  object
 4   education-num   32561 non-null  object
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  object
 11  capital-loss    32561 non-null  object
 12  hours-per-week  32561 non-null  object
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: object(15)
memory usage: 3.7+ MB

In [ ]:
for i in adult.columns:
    print(i,':','\n',adult[i].unique(),'\n')

age :
 ['39,' '50,' '38,' '53,' '28,' '37,' '49,' '52,' '31,' '42,' '30,' '23,'
 '32,' '40,' '34,' '25,' '43,' '54,' '35,' '59,' '56,' '19,' '20,' '45,'
 '22,' '48,' '21,' '24,' '57,' '44,' '41,' '29,' '18,' '47,' '46,' '36,'
 '79,' '27,' '67,' '33,' '76,' '17,' '55,' '61,' '70,' '64,' '71,' '68,'
 '66,' '51,' '58,' '26,' '60,' '90,' '75,' '65,' '77,' '62,' '63,' '80,'
 '72,' '74,' '69,' '73,' '81,' '78,' '88,' '82,' '83,' '84,' '85,' '86,'
 '87,']

workclass :
 ['State-gov,' 'Self-emp-not-inc,' 'Private,' 'Federal-gov,' 'Local-gov,'
 '?,' 'Self-emp-inc,' 'Without-pay,' 'Never-worked,']

fnlwgt :
 ['77516,' '83311,' '215646,' ... '34066,' '84661,' '257302,']

education :
 ['Bachelors,' 'HS-grad,' '11th,' 'Masters,' '9th,' 'Some-college,'
 'Assoc-acdm,' 'Assoc-voc,' '7th-8th,' 'Doctorate,' 'Prof-school,'
 '5th-6th,' '10th,' '1st-4th,' 'Preschool,' '12th,']

education-num :
 ['13,' '9,' '7,' '14,' '5,' '10,' '12,' '11,' '4,' '16,' '15,' '3,' '6,'
 '2,' '1,' '8,']

marital-status :
 ['Never-married,' 'Married-civ-spouse,' 'Divorced,'
 'Married-spouse-absent,' 'Separated,' 'Married-AF-spouse,' 'Widowed,']

occupation :
 ['Adm-clerical,' 'Exec-managerial,' 'Handlers-cleaners,' 'Prof-specialty,'
 'Other-service,' 'Sales,' 'Craft-repair,' 'Transport-moving,'
 'Farming-fishing,' 'Machine-op-inspct,' 'Tech-support,' '?,'
 'Protective-serv,' 'Armed-Forces,' 'Priv-house-serv,']

relationship :
 ['Not-in-family,' 'Husband,' 'Wife,' 'Own-child,' 'Unmarried,'
 'Other-relative,']

race :
 ['White,' 'Black,' 'Asian-Pac-Islander,' 'Amer-Indian-Eskimo,' 'Other,']

sex :
 ['Male,' 'Female,']

capital-gain :
 ['2174,' '0,' '14084,' '5178,' '5013,' '2407,' '14344,' '15024,' '7688,'
 '34095,' '4064,' '4386,' '7298,' '1409,' '3674,' '1055,' '3464,' '2050,'
 '2176,' '594,' '20051,' '6849,' '4101,' '1111,' '8614,' '3411,' '2597,'
 '25236,' '4650,' '9386,' '2463,' '3103,' '10605,' '2964,' '3325,' '2580,'
 '3471,' '4865,' '99999,' '6514,' '1471,' '2329,' '2105,' '2885,' '25124,'
 '10520,' '2202,' '2961,' '27828,' '6767,' '2228,' '1506,' '13550,'
 '2635,' '5556,' '4787,' '3781,' '3137,' '3818,' '3942,' '914,' '401,'
 '2829,' '2977,' '4934,' '2062,' '2354,' '5455,' '15020,' '1424,' '3273,'
 '22040,' '4416,' '3908,' '10566,' '991,' '4931,' '1086,' '7430,' '6497,'
 '114,' '7896,' '2346,' '3418,' '3432,' '2907,' '1151,' '2414,' '2290,'
 '15831,' '41310,' '4508,' '2538,' '3456,' '6418,' '1848,' '3887,' '5721,'
 '9562,' '1455,' '2036,' '1831,' '11678,' '2936,' '2993,' '7443,' '6360,'
 '1797,' '1173,' '4687,' '6723,' '2009,' '6097,' '2653,' '1639,' '18481,'
 '7978,' '2387,' '5060,']

capital-loss :
 ['0,' '2042,' '1408,' '1902,' '1573,' '1887,' '1719,' '1762,' '1564,'
 '2179,' '1816,' '1980,' '1977,' '1876,' '1340,' '2206,' '1741,' '1485,'
 '2339,' '2415,' '1380,' '1721,' '2051,' '2377,' '1669,' '2352,' '1672,'
 '653,' '2392,' '1504,' '2001,' '1590,' '1651,' '1628,' '1848,' '1740,'
 '2002,' '1579,' '2258,' '1602,' '419,' '2547,' '2174,' '2205,' '1726,'
 '2444,' '1138,' '2238,' '625,' '213,' '1539,' '880,' '1668,' '1092,'
 '1594,' '3004,' '2231,' '1844,' '810,' '2824,' '2559,' '2057,' '1974,'
 '974,' '2149,' '1825,' '1735,' '1258,' '2129,' '2603,' '2282,' '323,'
 '4356,' '2246,' '1617,' '1648,' '2489,' '3770,' '1755,' '3683,' '2267,'
 '2080,' '2457,' '155,' '3900,' '2201,' '1944,' '2467,' '2163,' '2754,'
 '2472,' '1411,']

hours-per-week :
 ['40,' '13,' '16,' '45,' '50,' '80,' '30,' '35,' '60,' '20,' '52,' '44,'
 '15,' '25,' '38,' '43,' '55,' '48,' '58,' '32,' '70,' '2,' '22,' '56,'
 '41,' '28,' '36,' '24,' '46,' '42,' '12,' '65,' '1,' '10,' '34,' '75,'
 '98,' '33,' '54,' '8,' '6,' '64,' '19,' '18,' '72,' '5,' '9,' '47,' '37,'
 '21,' '26,' '14,' '4,' '59,' '7,' '99,' '53,' '39,' '62,' '57,' '78,'
 '90,' '66,' '11,' '49,' '84,' '3,' '17,' '68,' '27,' '85,' '31,' '51,'
 '77,' '63,' '23,' '87,' '88,' '73,' '89,' '97,' '94,' '29,' '96,' '67,'
 '82,' '86,' '91,' '81,' '76,' '92,' '61,' '74,' '95,']

native-country :
 ['United-States,' 'Cuba,' 'Jamaica,' 'India,' '?,' 'Mexico,' 'South,'
 'Puerto-Rico,' 'Honduras,' 'England,' 'Canada,' 'Germany,' 'Iran,'
 'Philippines,' 'Italy,' 'Poland,' 'Columbia,' 'Cambodia,' 'Thailand,'
 'Ecuador,' 'Laos,' 'Taiwan,' 'Haiti,' 'Portugal,' 'Dominican-Republic,'
 'El-Salvador,' 'France,' 'Guatemala,' 'China,' 'Japan,' 'Yugoslavia,'
 'Peru,' 'Outlying-US(Guam-USVI-etc),' 'Scotland,' 'Trinadad&Tobago,'
 'Greece,' 'Nicaragua,' 'Vietnam,' 'Hong,' 'Ireland,' 'Hungary,'
 'Holand-Netherlands,']

income :
 ['<=50K' '>50K']

In [ ]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 1836
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 1843
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
native-country : 583
income : 0

In [ ]:
adult['workclass'].unique()

array(['State-gov,', 'Self-emp-not-inc,', 'Private,', 'Federal-gov,',
       'Local-gov,', '?,', 'Self-emp-inc,', 'Without-pay,',
       'Never-worked,'], dtype=object)

In [ ]:
adult['workclass'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 0
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 1843
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
native-country : 583
income : 0

In [ ]:
d=adult.describe(include='all')
d

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,32561,30725,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,73,8,21648,16,16,7,15,6,5,2,119,92,94,42,2
top,"36,","Private,","164190,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,898,22696,13,10501,10501,14976,4140,13193,27816,21790,29849,31042,15217,29170,24720

In [ ]:
adult.workclass.fillna(d['workclass'][3],inplace=True)

In [ ]:
adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
adult['occupation'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [100]:
adult['nativecountry'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.occupation.fillna(d['occupation'][3],inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [105]:
adult.describe(include='all')

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,31978,32561
unique,73,9,21648,16,16,7,15,6,5,2,119,92,94,41,2
top,"36,","Private,","164190,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,898,22696,13,10501,10501,14976,4140,13193,27816,21790,29849,31042,15217,29170,24720

In [108]:
adult.nativecountry.fillna(d['nativecountry'][3], inplace=True)
adult

KeyError: 'nativecountry'

In [96]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 0
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 0
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
nativecountry : 0
income : 0

In [103]:
adult.isnull().sum()

age                 0
workclass           0
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation          0
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
nativecountry     583
income              0
dtype: int64

POKEMON DATASET

In [3]:
pk=pd.read_csv(r"C:\Users\mishr\Downloads\pokemon.csv")
pk

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,True

In [6]:
pk.isnull().sum()

Name             0
Type 1           0
Type 2          84
Combat Power     0
HP               0
Attack           0
Defense          0
Sp. Atk          0
Sp. Def          0
Speed            0
Generation       0
Legendary        0
dtype: int64

In [9]:
d=pk.describe(include='all')
d

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
count,151,151,67,151.00000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.0,151
unique,151,15,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,Bulbasaur,Water,Poison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,1,28,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146
mean,NaN,NaN,NaN,407.07947,64.211921,72.549669,68.225166,67.139073,66.019868,69.000000,1.0,NaN
std,NaN,NaN,NaN,99.74384,28.590117,26.596162,26.916704,28.534199,24.197926,26.935726,0.0,NaN
min,NaN,NaN,NaN,195.00000,10.000000,5.000000,5.000000,15.000000,20.000000,15.000000,1.0,NaN
25%,NaN,NaN,NaN,320.00000,45.000000,51.000000,50.000000,45.000000,49.000000,46.500000,1.0,NaN
50%,NaN,NaN,NaN,405.00000,60.000000,70.000000,65.000000,65.000000,65.000000,70.000000,1.0,NaN
75%,NaN,NaN,NaN,490.00000,80.000000,90.000000,84.000000,87.500000,80.000000,90.000000,1.0,NaN
max,NaN,NaN,NaN,680.00000,250.000000,134.000000,180.000000,154.000000,125.000000,150.000000,1.0,NaN

In [13]:
for i in pk.columns:
    print(i,':','\n',pk[i].unique(),'\n')

Name :
 ['Bulbasaur' 'Ivysaur' 'Venusaur' 'Charmander' 'Charmeleon' 'Charizard'
 'Squirtle' 'Wartortle' 'Blastoise' 'Caterpie' 'Metapod' 'Butterfree'
 'Weedle' 'Kakuna' 'Beedrill' 'Pidgey' 'Pidgeotto' 'Pidgeot' 'Rattata'
 'Raticate' 'Spearow' 'Fearow' 'Ekans' 'Arbok' 'Pikachu' 'Raichu'
 'Sandshrew' 'Sandslash' 'Nidoran♀' 'Nidorina' 'Nidoqueen' 'Nidoran♂'
 'Nidorino' 'Nidoking' 'Clefairy' 'Clefable' 'Vulpix' 'Ninetales'
 'Jigglypuff' 'Wigglytuff' 'Zubat' 'Golbat' 'Oddish' 'Gloom' 'Vileplume'
 'Paras' 'Parasect' 'Venonat' 'Venomoth' 'Diglett' 'Dugtrio' 'Meowth'
 'Persian' 'Psyduck' 'Golduck' 'Mankey' 'Primeape' 'Growlithe' 'Arcanine'
 'Poliwag' 'Poliwhirl' 'Poliwrath' 'Abra' 'Kadabra' 'Alakazam' 'Machop'
 'Machoke' 'Machamp' 'Bellsprout' 'Weepinbell' 'Victreebel' 'Tentacool'
 'Tentacruel' 'Geodude' 'Graveler' 'Golem' 'Ponyta' 'Rapidash' 'Slowpoke'
 'Slowbro' 'Magnemite' 'Magneton' "Farfetch'd" 'Doduo' 'Dodrio' 'Seel'
 'Dewgong' 'Grimer' 'Muk' 'Shellder' 'Cloyster' 'Gastly' 'Haunter'
 'Gengar' 'Onix' 'Drowzee' 'Hypno' 'Krabby' 'Kingler' 'Voltorb'
 'Electrode' 'Exeggcute' 'Exeggutor' 'Cubone' 'Marowak' 'Hitmonlee'
 'Hitmonchan' 'Lickitung' 'Koffing' 'Weezing' 'Rhyhorn' 'Rhydon' 'Chansey'
 'Tangela' 'Kangaskhan' 'Horsea' 'Seadra' 'Goldeen' 'Seaking' 'Staryu'
 'Starmie' 'Mr. Mime' 'Scyther' 'Jynx' 'Electabuzz' 'Magmar' 'Pinsir'
 'Tauros' 'Magikarp' 'Gyarados' 'Lapras' 'Ditto' 'Eevee' 'Vaporeon'
 'Jolteon' 'Flareon' 'Porygon' 'Omanyte' 'Omastar' 'Kabuto' 'Kabutops'
 'Aerodactyl' 'Snorlax' 'Articuno' 'Zapdos' 'Moltres' 'Dratini'
 'Dragonair' 'Dragonite' 'Mewtwo' 'Mew']

Type 1 :
 ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon']

Type 2 :
 ['Poison' nan 'Flying' 'Ground' 'Fairy' 'Grass' 'Fighting' 'Psychic'
 'Steel' 'Ice' 'Rock' 'Water']

Combat Power :
 [318 405 525 309 534 314 530 195 205 395 251 349 479 253 413 262 442 288
 438 320 485 300 450 275 365 505 273 323 483 299 270 435 245 455 490 285
 305 265 290 440 500 350 555 385 510 310 400 390 335 515 495 410 315 325
 465 352 460 475 328 330 480 520 425 340 345 295 200 540 535 355 580 420
 600 680]

HP :
 [ 45  60  80  39  58  78  44  59  79  50  40  65  63  83  30  55  35  75
  70  90  46  61  81  95  38  73 115 140  10  25  52 105  85 250  20 130
  48 160  41  91 106 100]

Attack :
 [ 49  62  82  52  64  84  48  63  83  30  20  45  35  25  90  60  80  56
  81  85  55  75 100  47  92  57  72 102  70  41  76  50  65  95 105 110
 130  40 120  73   5  67 125  10 115 134]

Defense :
 [ 49  63  83  43  58  78  65  80 100  35  55  50  30  40  75  60  44  69
  85 110  52  67  87  57  77  48  73  20  45  70  25  95  15 115 130 180
 160  90  53  79 120   5 125 105]

Sp. Atk :
 [ 65  80 100  60 109  50  85  20  25  90  45  35  70  31  61  40  55  75
  95  81  30 110 105 120 135  58 115 130  43  73 125  15  48 154]

Sp. Def :
 [ 65  80 100  50  85  64 105  20  25  35  70  31  61  54  79  30  55  40
  75  90  45  95  60 120  62 115 110  48 125]

Speed :
 [ 45  60  80  65 100  43  58  78  30  70  50  35  75  56  71 101  72  97
  55  90 110  40  41  76  85  20  25  95 120 115 105  15  42  67 150  87
  63  68  93  81  48 130]

Generation :
 [1]

Legendary :
 [False  True]

In [12]:
pk['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Ground', 'Fairy', 'Grass', 'Fighting',
       'Psychic', 'Steel', 'Ice', 'Rock', 'Water'], dtype=object)

In [15]:
pk['Type 2'].fillna(d['Type 2'][3],inplace=True)
pk

C:\Users\mishr\AppData\Local\Temp\ipykernel_10344\2461627003.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pk['Type 2'].fillna(d['Type 2'][3],inplace=True)

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,19,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,19,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,19,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,19,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,19,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,19,600,100,100,100,100,100,100,1,True

In [16]:
pk.isnull().sum()

Name            0
Type 1          0
Type 2          0
Combat Power    0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

TITANIC DATASHEET

In [19]:
tit=pd.read_csv(r"C:\Users\mishr\Downloads\titanic dataset.csv")
tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
d=tit.describe(include='all')
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [20]:
tit.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
tit.Age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [29]:
tit.Age.fillna(d['Age'][5],inplace=True)
tit

C:\Users\mishr\AppData\Local\Temp\ipykernel_10344\898740937.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tit.Age.fillna(d['Age'][5],inplace=True)
C:\Users\mishr\AppData\Local\Temp\ipykernel_10344\898740937.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tit.Age.fillna(d['Age'][5],inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,14.526497,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [30]:
tit.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
tit.Age.fillna(d['Cabin'][4],inplace=True)
tit

C:\Users\mishr\AppData\Local\Temp\ipykernel_10344\3110153719.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tit.Age.fillna(d['Cabin'][4],inplace=True)
C:\Users\mishr\AppData\Local\Temp\ipykernel_10344\3110153719.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tit.Age.fillna(d['Cabin'][4],inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,14.526497,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [38]:
tit.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64