<h1>PANDAS LIBRARY</H1>

Installing and importing Pandas

In [15]:
#pandas is a library used for data manipulation and analysis. It provides data structures and functions needed to manipulate structured data, such as tabular data in the form of DataFrames.
#it is of two types 1) series(single column of data)
#                   2) dataframe
import pandas as pd
import numpy as np

1) Series creation

In [16]:
#creating series
s=pd.Series([1,2,3,4,5])
print(s)
type(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

In [17]:
s=pd.Series(['a','b','c','d','e'])
print(s)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [18]:
s=pd.Series(['a','b','c','d','e'],index =[1,2,3,11,5]) # we can set index of objects according to us
print(s)

1     a
2     b
3     c
11    d
5     e
dtype: object

In [19]:
print(s[11]) # indexing
print(s[1:4]) #slicing (by default we have to give the general series of index while slicing)

d
2     b
3     c
11    d
dtype: object

2) Conversion of different datatypes to series

In [20]:
#tuple to series
t= pd.Series((13,5,3,5)) 
print(t)

0    13
1     5
2     3
3     5
dtype: int64

In [21]:
#set to series
s=pd.Series({2,3,4,4,5,})
s# set can't be used as series it is unordered

TypeError: 'set' type is unordered

In [ ]:
#dictonary to series
d=pd.Series({'a':1,'b':2,'c':3})
print(d) #key becomes index position and value becomes the object
d=pd.Series({'a':1,'b':2,'c':3},index=['e','f','a','b'])
print(d)
d['b']# indexing
d['a':'b':1] #slicing

a    1
b    2
c    3
dtype: int64
e    NaN
f    NaN
a    1.0
b    2.0
dtype: float64

a    1.0
b    2.0
dtype: float64

3)Dataframes creation

In [ ]:
#creating dataframe
d={'name':['ram','hari','sita','gita'],'roll':[101,102,103,104],'course':['AIML','PYTHON','DSA','C']} #dataframes are created using dictionary
print(d)
df=pd.DataFrame(d)
print(df)

{'name': ['ram', 'hari', 'sita', 'gita'], 'roll': [101, 102, 103, 104], 'course': ['AIML', 'PYTHON', 'DSA', 'C']}
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
print(df.name[2]) #indexing syntax:- var.colname[index]
print(df.iloc[::1]) #this is slicing in dataframes
print (df.iloc[2::])
print(df.iloc[::,2])

sita
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C
   name  roll course
2  sita   103    DSA
3  gita   104      C
0      AIML
1    PYTHON
2       DSA
3         C
Name: course, dtype: object

In [ ]:
print(df.head()) # it will give us the first 5 rows of dataframe by default and if we want to give the number of rows we want to see then we can give the number in the head function like this df.head(3) it will give us the first 3 rows of dataframe
print(df.tail()) # it will give us the last 5 rows of dataframe by default and if we want to give the number of rows we want to see then we can give the number in the tail function like this df.tail(3) it will give us the last 3 rows of dataframe

   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C
   name  roll  course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
df.sample(3) # it will give us a random row from the dataframe and if we want to give the number of rows we want to see then we can give the number in the sample function like this df.sample(3) it will give us 3 random rows from the dataframe

   name  roll  course
0   ram   101    AIML
3  gita   104       C
1  hari   102  PYTHON

In [ ]:
df=df.rename(columns={'name':'Name','roll':'Roll','course':'Course'}) # renaming the columns of dataframe
print(df)

   Name  Roll  Course
0   ram   101    AIML
1  hari   102  PYTHON
2  sita   103     DSA
3  gita   104       C

In [ ]:
df=df.set_index('Roll') # setting the index of dataframe to name column
print(df)
#df=df.set_index('Course',inplace=True) # setting the index of dataframe to course column and inplace is used to make the changes in the original dataframe
#print(df)

      Name  Course
Roll
101    ram    AIML
102   hari  PYTHON
103   sita     DSA
104   gita       C

In [ ]:
df.reset_index('Roll')
df

      Name  Course
Roll
101    ram    AIML
102   hari  PYTHON
103   sita     DSA
104   gita       C

In [ ]:
df=pd.DataFrame({'Days':[1,2,3,4,5],'Places':['Paris','Tokyo',np.nan,'New York','Sydney'],'Visitors':[3425,4523,3244,4324,4342]})
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3       NaN      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False    True     False
3  False   False     False
4  False   False     False

In [ ]:
df.isnull().sum() #this is used to check the no.of missing values

Days        0
Places      1
Visitors    0
dtype: int64

In [ ]:
df.Places.fillna('Delhi')
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3       NaN      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
df.Places.fillna('Delhi',inplace=True)
df

   Days    Places  Visitors
0     1     Paris      3425
1     2     Tokyo      4523
2     3     Delhi      3244
3     4  New York      4324
4     5    Sydney      4342

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df.dtypes

Days         int64
Places      object
Visitors     int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   Places    5 non-null      object
 2   Visitors  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
df.Places.unique()

array(['Paris', 'Tokyo', 'Delhi', 'New York', 'Sydney'], dtype=object)

In [ ]:
df.columns

Index(['Days', 'Places', 'Visitors'], dtype='object')

In [ ]:
for i in df.columns:
    print(df[i].unique())

[1 2 3 4 5]
['Paris' 'Tokyo' 'Delhi' 'New York' 'Sydney']
[3425 4523 3244 4324 4342]

In [ ]:
df.Visitors.mean()

np.float64(3971.6)

In [ ]:
df.Visitors.min()

3244

In [ ]:
print(df[df["Visitors"] == df["Visitors"].min()])

   Days Places  Visitors
2     3  Delhi      3244

In [ ]:
df.describe(include='all')

            Days Places    Visitors
count   5.000000      5     5.00000
unique       NaN      5         NaN
top          NaN  Paris         NaN
freq         NaN      1         NaN
mean    3.000000    NaN  3971.60000
std     1.581139    NaN   590.25359
min     1.000000    NaN  3244.00000
25%     2.000000    NaN  3425.00000
50%     3.000000    NaN  4324.00000
75%     4.000000    NaN  4342.00000
max     5.000000    NaN  4523.00000

<pre>Data cleaning<br>
1)read the data<br>
2)rename the col name if req<br>
3)check missing or null values<br>
4)check datatype/info<br>
5)check unique values<br>
6)replace the missing values<br>
7)by taking the value from the describe value</pre>

ADULT DATASET

In [ ]:
adult=pd.read_csv(r"C:\Users\mishr\Downloads\adult\adult.data",header=None,delim_whitespace=True)
adult

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.columns= ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','nativecountry','income']
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
adult.dtypes

age               object
workclass         object
fnlwgt            object
education         object
education-num     object
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain      object
capital-loss      object
hours-per-week    object
native-country    object
income            object
dtype: object

In [ ]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  object
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  object
 3   education       32561 non-null  object
 4   education-num   32561 non-null  object
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  object
 11  capital-loss    32561 non-null  object
 12  hours-per-week  32561 non-null  object
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: object(15)
memory usage: 3.7+ MB

In [ ]:
for i in adult.columns:
    print(i,':','\n',adult[i].unique(),'\n')

age :
 ['39,' '50,' '38,' '53,' '28,' '37,' '49,' '52,' '31,' '42,' '30,' '23,'
 '32,' '40,' '34,' '25,' '43,' '54,' '35,' '59,' '56,' '19,' '20,' '45,'
 '22,' '48,' '21,' '24,' '57,' '44,' '41,' '29,' '18,' '47,' '46,' '36,'
 '79,' '27,' '67,' '33,' '76,' '17,' '55,' '61,' '70,' '64,' '71,' '68,'
 '66,' '51,' '58,' '26,' '60,' '90,' '75,' '65,' '77,' '62,' '63,' '80,'
 '72,' '74,' '69,' '73,' '81,' '78,' '88,' '82,' '83,' '84,' '85,' '86,'
 '87,']

workclass :
 ['State-gov,' 'Self-emp-not-inc,' 'Private,' 'Federal-gov,' 'Local-gov,'
 '?,' 'Self-emp-inc,' 'Without-pay,' 'Never-worked,']

fnlwgt :
 ['77516,' '83311,' '215646,' ... '34066,' '84661,' '257302,']

education :
 ['Bachelors,' 'HS-grad,' '11th,' 'Masters,' '9th,' 'Some-college,'
 'Assoc-acdm,' 'Assoc-voc,' '7th-8th,' 'Doctorate,' 'Prof-school,'
 '5th-6th,' '10th,' '1st-4th,' 'Preschool,' '12th,']

education-num :
 ['13,' '9,' '7,' '14,' '5,' '10,' '12,' '11,' '4,' '16,' '15,' '3,' '6,'
 '2,' '1,' '8,']

marital-status :
 ['Never-married,' 'Married-civ-spouse,' 'Divorced,'
 'Married-spouse-absent,' 'Separated,' 'Married-AF-spouse,' 'Widowed,']

occupation :
 ['Adm-clerical,' 'Exec-managerial,' 'Handlers-cleaners,' 'Prof-specialty,'
 'Other-service,' 'Sales,' 'Craft-repair,' 'Transport-moving,'
 'Farming-fishing,' 'Machine-op-inspct,' 'Tech-support,' '?,'
 'Protective-serv,' 'Armed-Forces,' 'Priv-house-serv,']

relationship :
 ['Not-in-family,' 'Husband,' 'Wife,' 'Own-child,' 'Unmarried,'
 'Other-relative,']

race :
 ['White,' 'Black,' 'Asian-Pac-Islander,' 'Amer-Indian-Eskimo,' 'Other,']

sex :
 ['Male,' 'Female,']

capital-gain :
 ['2174,' '0,' '14084,' '5178,' '5013,' '2407,' '14344,' '15024,' '7688,'
 '34095,' '4064,' '4386,' '7298,' '1409,' '3674,' '1055,' '3464,' '2050,'
 '2176,' '594,' '20051,' '6849,' '4101,' '1111,' '8614,' '3411,' '2597,'
 '25236,' '4650,' '9386,' '2463,' '3103,' '10605,' '2964,' '3325,' '2580,'
 '3471,' '4865,' '99999,' '6514,' '1471,' '2329,' '2105,' '2885,' '25124,'
 '10520,' '2202,' '2961,' '27828,' '6767,' '2228,' '1506,' '13550,'
 '2635,' '5556,' '4787,' '3781,' '3137,' '3818,' '3942,' '914,' '401,'
 '2829,' '2977,' '4934,' '2062,' '2354,' '5455,' '15020,' '1424,' '3273,'
 '22040,' '4416,' '3908,' '10566,' '991,' '4931,' '1086,' '7430,' '6497,'
 '114,' '7896,' '2346,' '3418,' '3432,' '2907,' '1151,' '2414,' '2290,'
 '15831,' '41310,' '4508,' '2538,' '3456,' '6418,' '1848,' '3887,' '5721,'
 '9562,' '1455,' '2036,' '1831,' '11678,' '2936,' '2993,' '7443,' '6360,'
 '1797,' '1173,' '4687,' '6723,' '2009,' '6097,' '2653,' '1639,' '18481,'
 '7978,' '2387,' '5060,']

capital-loss :
 ['0,' '2042,' '1408,' '1902,' '1573,' '1887,' '1719,' '1762,' '1564,'
 '2179,' '1816,' '1980,' '1977,' '1876,' '1340,' '2206,' '1741,' '1485,'
 '2339,' '2415,' '1380,' '1721,' '2051,' '2377,' '1669,' '2352,' '1672,'
 '653,' '2392,' '1504,' '2001,' '1590,' '1651,' '1628,' '1848,' '1740,'
 '2002,' '1579,' '2258,' '1602,' '419,' '2547,' '2174,' '2205,' '1726,'
 '2444,' '1138,' '2238,' '625,' '213,' '1539,' '880,' '1668,' '1092,'
 '1594,' '3004,' '2231,' '1844,' '810,' '2824,' '2559,' '2057,' '1974,'
 '974,' '2149,' '1825,' '1735,' '1258,' '2129,' '2603,' '2282,' '323,'
 '4356,' '2246,' '1617,' '1648,' '2489,' '3770,' '1755,' '3683,' '2267,'
 '2080,' '2457,' '155,' '3900,' '2201,' '1944,' '2467,' '2163,' '2754,'
 '2472,' '1411,']

hours-per-week :
 ['40,' '13,' '16,' '45,' '50,' '80,' '30,' '35,' '60,' '20,' '52,' '44,'
 '15,' '25,' '38,' '43,' '55,' '48,' '58,' '32,' '70,' '2,' '22,' '56,'
 '41,' '28,' '36,' '24,' '46,' '42,' '12,' '65,' '1,' '10,' '34,' '75,'
 '98,' '33,' '54,' '8,' '6,' '64,' '19,' '18,' '72,' '5,' '9,' '47,' '37,'
 '21,' '26,' '14,' '4,' '59,' '7,' '99,' '53,' '39,' '62,' '57,' '78,'
 '90,' '66,' '11,' '49,' '84,' '3,' '17,' '68,' '27,' '85,' '31,' '51,'
 '77,' '63,' '23,' '87,' '88,' '73,' '89,' '97,' '94,' '29,' '96,' '67,'
 '82,' '86,' '91,' '81,' '76,' '92,' '61,' '74,' '95,']

native-country :
 ['United-States,' 'Cuba,' 'Jamaica,' 'India,' '?,' 'Mexico,' 'South,'
 'Puerto-Rico,' 'Honduras,' 'England,' 'Canada,' 'Germany,' 'Iran,'
 'Philippines,' 'Italy,' 'Poland,' 'Columbia,' 'Cambodia,' 'Thailand,'
 'Ecuador,' 'Laos,' 'Taiwan,' 'Haiti,' 'Portugal,' 'Dominican-Republic,'
 'El-Salvador,' 'France,' 'Guatemala,' 'China,' 'Japan,' 'Yugoslavia,'
 'Peru,' 'Outlying-US(Guam-USVI-etc),' 'Scotland,' 'Trinadad&Tobago,'
 'Greece,' 'Nicaragua,' 'Vietnam,' 'Hong,' 'Ireland,' 'Hungary,'
 'Holand-Netherlands,']

income :
 ['<=50K' '>50K']

In [ ]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 1836
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 1843
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
native-country : 583
income : 0

In [ ]:
adult['workclass'].unique()

array(['State-gov,', 'Self-emp-not-inc,', 'Private,', 'Federal-gov,',
       'Local-gov,', '?,', 'Self-emp-inc,', 'Without-pay,',
       'Never-worked,'], dtype=object)

In [ ]:
adult['workclass'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 0
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 1843
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
native-country : 583
income : 0

In [ ]:
d=adult.describe(include='all')
d

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,32561,30725,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,73,8,21648,16,16,7,15,6,5,2,119,92,94,42,2
top,"36,","Private,","164190,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,898,22696,13,10501,10501,14976,4140,13193,27816,21790,29849,31042,15217,29170,24720

In [ ]:
adult.workclass.fillna(d['workclass'][3],inplace=True)

In [ ]:
adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
adult['occupation'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult['nativecountry'].replace('?,',np.nan,inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.occupation.fillna(d['occupation'][3],inplace=True)
adult

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,"27,","Private,","257302,","Assoc-acdm,","12,","Married-civ-spouse,","Tech-support,","Wife,","White,","Female,","0,","0,","38,","United-States,",<=50K
32557,"40,","Private,","154374,","HS-grad,","9,","Married-civ-spouse,","Machine-op-inspct,","Husband,","White,","Male,","0,","0,","40,","United-States,",>50K
32558,"58,","Private,","151910,","HS-grad,","9,","Widowed,","Adm-clerical,","Unmarried,","White,","Female,","0,","0,","40,","United-States,",<=50K
32559,"22,","Private,","201490,","HS-grad,","9,","Never-married,","Adm-clerical,","Own-child,","White,","Male,","0,","0,","20,","United-States,",<=50K
32560,"52,","Self-emp-inc,","287927,","HS-grad,","9,","Married-civ-spouse,","Exec-managerial,","Wife,","White,","Female,","15024,","0,","40,","United-States,",>50K

In [ ]:
adult.describe(include='all')

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,nativecountry,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,31978,32561
unique,73,9,21648,16,16,7,15,6,5,2,119,92,94,41,2
top,"36,","Private,","164190,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,898,22696,13,10501,10501,14976,4140,13193,27816,21790,29849,31042,15217,29170,24720

In [ ]:
adult.nativecountry.fillna(d['nativecountry'][3], inplace=True)
adult

KeyError: 'nativecountry'

In [ ]:
for i in adult.columns:
    print(i,':',sum(adult[i]=='?,'))

age : 0
workclass : 0
fnlwgt : 0
education : 0
education-num : 0
marital-status : 0
occupation : 0
relationship : 0
race : 0
sex : 0
capital-gain : 0
capital-loss : 0
hours-per-week : 0
nativecountry : 0
income : 0

In [ ]:
adult.isnull().sum()

age                 0
workclass           0
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation          0
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
nativecountry     583
income              0
dtype: int64